$script = <<-SCRIPT
sudo apt-get update -y
sudo apt-get install -y ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -a -G docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "docker" do |dock1|
    dock1.vm.hostname = "docker-server"
    dock1.vm.provider "virtualbox" do |vb|
      vb.name = "docker-server"
      vb.cpus = 4
      vb.memory = 8192
    end
    ubuntu.vm.network "forwarded_port", guest: 80, host: 80 
    dock1.vm.network "private_network", ip: "192.168.33.150"
    dock1.vm.provision "shell", inline: $script
  end
end